name: flutter_isolate_example
description: Demonstrates how to use the flutter_isolate plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_isolate:
    path: ../
  path_provider: ^2.1.2
  flutter_downloader: ^1.11.6

flutter:
  uses-material-design: true
