name: flutter_isolate
description: FlutterIsolate provides a way to launch dart isolate in flutter that work with flutter plugins.
version: 2.0.5-pre
homepage: https://github.com/rmawatson/flutter_isolate

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rmawatson.flutterisolate
        pluginClass: FlutterIsolatePlugin
      ios:
        pluginClass: FlutterIsolatePlugin
      macos:
        pluginClass: FlutterIsolatePluginMacOS
